# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpcbasic0_pb2 as grpcbasic0__pb2


class UserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.NewUser = channel.unary_unary(
        '/pb.UserService/NewUser',
        request_serializer=grpcbasic0__pb2.NewUserReq.SerializeToString,
        response_deserializer=grpcbasic0__pb2.UserResp.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/pb.UserService/GetUser',
        request_serializer=grpcbasic0__pb2.GetUserReq.SerializeToString,
        response_deserializer=grpcbasic0__pb2.UserResp.FromString,
        )
    self.GetUsers = channel.unary_unary(
        '/pb.UserService/GetUsers',
        request_serializer=grpcbasic0__pb2.GetUsersReq.SerializeToString,
        response_deserializer=grpcbasic0__pb2.UsersResp.FromString,
        )


class UserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def NewUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NewUser': grpc.unary_unary_rpc_method_handler(
          servicer.NewUser,
          request_deserializer=grpcbasic0__pb2.NewUserReq.FromString,
          response_serializer=grpcbasic0__pb2.UserResp.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=grpcbasic0__pb2.GetUserReq.FromString,
          response_serializer=grpcbasic0__pb2.UserResp.SerializeToString,
      ),
      'GetUsers': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=grpcbasic0__pb2.GetUsersReq.FromString,
          response_serializer=grpcbasic0__pb2.UsersResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
