// Code generated by protoc-gen-go.
// source: grpcbasic0.proto
// DO NOT EDIT!

/*
Package idl is a generated protocol buffer package.

It is generated from these files:
	grpcbasic0.proto

It has these top-level messages:
	User
	UserRecordReq
	UserGetReq
	Users
	UsersListReq
*/
package idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age     int64  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Fortune string `protobuf:"bytes,4,opt,name=fortune" json:"fortune,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UserRecordReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *UserRecordReq) Reset()                    { *m = UserRecordReq{} }
func (m *UserRecordReq) String() string            { return proto.CompactTextString(m) }
func (*UserRecordReq) ProtoMessage()               {}
func (*UserRecordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UserGetReq struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *UserGetReq) Reset()                    { *m = UserGetReq{} }
func (m *UserGetReq) String() string            { return proto.CompactTextString(m) }
func (*UserGetReq) ProtoMessage()               {}
func (*UserGetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Users struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *Users) Reset()                    { *m = Users{} }
func (m *Users) String() string            { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()               {}
func (*Users) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UsersListReq struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Start int64 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Down  bool  `protobuf:"varint,3,opt,name=down" json:"down,omitempty"`
}

func (m *UsersListReq) Reset()                    { *m = UsersListReq{} }
func (m *UsersListReq) String() string            { return proto.CompactTextString(m) }
func (*UsersListReq) ProtoMessage()               {}
func (*UsersListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*User)(nil), "idl.User")
	proto.RegisterType((*UserRecordReq)(nil), "idl.UserRecordReq")
	proto.RegisterType((*UserGetReq)(nil), "idl.UserGetReq")
	proto.RegisterType((*Users)(nil), "idl.Users")
	proto.RegisterType((*UsersListReq)(nil), "idl.UsersListReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for UserService service

type UserServiceClient interface {
	RecordUser(ctx context.Context, in *UserRecordReq, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *UserGetReq, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *UsersListReq, opts ...grpc.CallOption) (*Users, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RecordUser(ctx context.Context, in *UserRecordReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/idl.UserService/RecordUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserGetReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/idl.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *UsersListReq, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := grpc.Invoke(ctx, "/idl.UserService/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	RecordUser(context.Context, *UserRecordReq) (*User, error)
	GetUser(context.Context, *UserGetReq) (*User, error)
	ListUsers(context.Context, *UsersListReq) (*Users, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RecordUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RecordUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.UserService/RecordUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RecordUser(ctx, req.(*UserRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*UsersListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordUser",
			Handler:    _UserService_RecordUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("grpcbasic0.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0xb1, 0x6e, 0xea, 0x30,
	0x18, 0x85, 0xe5, 0x04, 0x2e, 0xe4, 0xe7, 0xc2, 0xe5, 0x1a, 0x86, 0x14, 0x21, 0x15, 0x79, 0x8a,
	0x18, 0x48, 0x4b, 0xd5, 0x85, 0x89, 0x8d, 0xa5, 0xea, 0x90, 0xaa, 0xdd, 0x43, 0xec, 0x46, 0x96,
	0xa8, 0x4d, 0x6d, 0x43, 0x87, 0xaa, 0x4b, 0x5f, 0xa1, 0x8f, 0xc6, 0x2b, 0xf4, 0x41, 0x2a, 0xdb,
	0x24, 0x54, 0xed, 0xf6, 0xfb, 0xcf, 0x39, 0x9f, 0xcf, 0xb1, 0x02, 0xfd, 0x52, 0x6d, 0x8b, 0x75,
	0xae, 0x79, 0x71, 0x31, 0xdb, 0x2a, 0x69, 0x24, 0x0e, 0x39, 0xdd, 0x8c, 0xc6, 0xa5, 0x94, 0xe5,
	0x86, 0xa5, 0xf9, 0x96, 0xa7, 0xb9, 0x10, 0xd2, 0xe4, 0x86, 0x4b, 0xa1, 0xbd, 0x84, 0x3c, 0x40,
	0xe3, 0x5e, 0x33, 0x85, 0x7b, 0x10, 0x70, 0x1a, 0xa3, 0x09, 0x4a, 0xc2, 0x2c, 0xe0, 0x14, 0x63,
	0x68, 0x88, 0xfc, 0x89, 0xc5, 0xc1, 0x04, 0x25, 0x51, 0xe6, 0x66, 0xdc, 0x87, 0x30, 0x2f, 0x59,
	0x1c, 0x3a, 0x91, 0x1d, 0x71, 0x0c, 0xad, 0x47, 0xa9, 0xcc, 0x4e, 0xb0, 0xb8, 0xe1, 0x84, 0xd5,
	0x91, 0x5c, 0x43, 0xd7, 0x72, 0x33, 0x56, 0x48, 0x45, 0x33, 0xf6, 0x5c, 0x03, 0xd1, 0x6f, 0x60,
	0x50, 0x03, 0xc9, 0x18, 0xc0, 0xda, 0x56, 0xcc, 0x58, 0xcf, 0x8f, 0x50, 0x24, 0x81, 0xa6, 0xfd,
	0xaa, 0xf1, 0x39, 0x34, 0x77, 0x76, 0x88, 0xd1, 0x24, 0x4c, 0x3a, 0xf3, 0x68, 0xc6, 0xe9, 0x66,
	0xe6, 0xee, 0xf3, 0x7b, 0x72, 0x0b, 0x7f, 0x9d, 0xf2, 0x86, 0x6b, 0x47, 0x1a, 0x42, 0xb3, 0x90,
	0x3b, 0x61, 0x8e, 0x30, 0x7f, 0xb0, 0x5b, 0x6d, 0x72, 0x65, 0x8e, 0x09, 0xfc, 0xc1, 0x26, 0xa5,
	0xf2, 0x45, 0xb8, 0x9e, 0xed, 0xcc, 0xcd, 0xf3, 0x03, 0x82, 0x8e, 0x05, 0xde, 0x31, 0xb5, 0xe7,
	0x05, 0xc3, 0x4b, 0x00, 0x5f, 0xcd, 0x3d, 0x1e, 0x3e, 0xdd, 0x5f, 0xf5, 0x1d, 0x9d, 0x32, 0x91,
	0xc1, 0xfb, 0xe1, 0xf3, 0x23, 0xe8, 0x92, 0x76, 0xba, 0xbf, 0x4c, 0x6d, 0xbe, 0x05, 0x9a, 0xe2,
	0x25, 0xb4, 0x56, 0xcc, 0x38, 0xfb, 0xbf, 0x5a, 0xea, 0x7b, 0x7f, 0xf7, 0x9e, 0x39, 0xef, 0x80,
	0xf4, 0x2a, 0xaf, 0x4e, 0x5f, 0x39, 0x7d, 0xf3, 0x84, 0xc8, 0xd6, 0xf3, 0x2f, 0xf2, 0xbf, 0xb6,
	0x54, 0x9d, 0x47, 0x70, 0x5a, 0x91, 0xa1, 0xc3, 0xf4, 0x48, 0x54, 0x63, 0x16, 0x68, 0xba, 0xfe,
	0xe3, 0xfe, 0x81, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xa9, 0x36, 0xb6, 0x3a, 0x02,
	0x00, 0x00,
}
