// Code generated by protoc-gen-go.
// source: grpcbasic0.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

User Service

User Service API provides create, read, and read (many) access to a list of
users.

It is generated from these files:
	grpcbasic0.proto

It has these top-level messages:
	UserResp
	NewUserReq
	GetUserReq
	UsersResp
	GetUsersReq
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserResp struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age     int64  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Fortune string `protobuf:"bytes,4,opt,name=fortune" json:"fortune,omitempty"`
}

func (m *UserResp) Reset()                    { *m = UserResp{} }
func (m *UserResp) String() string            { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()               {}
func (*UserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResp) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserResp) GetFortune() string {
	if m != nil {
		return m.Fortune
	}
	return ""
}

type NewUserReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *NewUserReq) Reset()                    { *m = NewUserReq{} }
func (m *NewUserReq) String() string            { return proto.CompactTextString(m) }
func (*NewUserReq) ProtoMessage()               {}
func (*NewUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetUserReq struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserReq) Reset()                    { *m = GetUserReq{} }
func (m *GetUserReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()               {}
func (*GetUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UsersResp struct {
	Users []*UserResp `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UsersResp) Reset()                    { *m = UsersResp{} }
func (m *UsersResp) String() string            { return proto.CompactTextString(m) }
func (*UsersResp) ProtoMessage()               {}
func (*UsersResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UsersResp) GetUsers() []*UserResp {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUsersReq struct {
	Start int64 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Desc  bool  `protobuf:"varint,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *GetUsersReq) Reset()                    { *m = GetUsersReq{} }
func (m *GetUsersReq) String() string            { return proto.CompactTextString(m) }
func (*GetUsersReq) ProtoMessage()               {}
func (*GetUsersReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUsersReq) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetUsersReq) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUsersReq) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

func init() {
	proto.RegisterType((*UserResp)(nil), "pb.UserResp")
	proto.RegisterType((*NewUserReq)(nil), "pb.NewUserReq")
	proto.RegisterType((*GetUserReq)(nil), "pb.GetUserReq")
	proto.RegisterType((*UsersResp)(nil), "pb.UsersResp")
	proto.RegisterType((*GetUsersReq)(nil), "pb.GetUsersReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	NewUser(ctx context.Context, in *NewUserReq, opts ...grpc.CallOption) (*UserResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error)
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*UsersResp, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) NewUser(ctx context.Context, in *NewUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := grpc.Invoke(ctx, "/pb.UserService/NewUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := grpc.Invoke(ctx, "/pb.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*UsersResp, error) {
	out := new(UsersResp)
	err := grpc.Invoke(ctx, "/pb.UserService/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	NewUser(context.Context, *NewUserReq) (*UserResp, error)
	GetUser(context.Context, *GetUserReq) (*UserResp, error)
	GetUsers(context.Context, *GetUsersReq) (*UsersResp, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).NewUser(ctx, req.(*NewUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUser",
			Handler:    _UserService_NewUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcbasic0.proto",
}

func init() { proto.RegisterFile("grpcbasic0.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xbf, 0x4e, 0xeb, 0x30,
	0x14, 0xc6, 0xe5, 0xa4, 0xbd, 0x4d, 0x4f, 0x6e, 0xff, 0xdc, 0x73, 0x41, 0x8a, 0xaa, 0x0e, 0x95,
	0xa7, 0x8a, 0xa1, 0x81, 0xb2, 0x21, 0x60, 0x65, 0x82, 0x21, 0x88, 0x85, 0xcd, 0x49, 0x4c, 0x64,
	0x09, 0xe2, 0x10, 0xbb, 0x65, 0x40, 0x2c, 0xbc, 0x02, 0x6f, 0xc5, 0xca, 0x2b, 0xf0, 0x20, 0xc8,
	0x4e, 0xdc, 0x42, 0xd9, 0xce, 0x97, 0x73, 0xbe, 0x5f, 0xbe, 0x2f, 0x0a, 0x8c, 0x8b, 0xba, 0xca,
	0x52, 0xa6, 0x44, 0x76, 0xb8, 0xa8, 0x6a, 0xa9, 0x25, 0x7a, 0x55, 0x3a, 0x99, 0x16, 0x52, 0x16,
	0xf7, 0x3c, 0x66, 0x95, 0x88, 0x59, 0x59, 0x4a, 0xcd, 0xb4, 0x90, 0xa5, 0x6a, 0x2e, 0xe8, 0x2d,
	0x04, 0x37, 0x8a, 0xd7, 0x09, 0x57, 0x15, 0x0e, 0xc1, 0x13, 0x79, 0x44, 0x66, 0x64, 0xee, 0x27,
	0x9e, 0xc8, 0x11, 0xa1, 0x53, 0xb2, 0x07, 0x1e, 0x79, 0x33, 0x32, 0xef, 0x27, 0x76, 0xc6, 0x31,
	0xf8, 0xac, 0xe0, 0x91, 0x6f, 0x8f, 0xcc, 0x88, 0x11, 0xf4, 0xee, 0x64, 0xad, 0x57, 0x25, 0x8f,
	0x3a, 0xf6, 0xd0, 0x49, 0xba, 0x04, 0xb8, 0xe2, 0x4f, 0x0d, 0xfe, 0x71, 0x43, 0x23, 0xbf, 0x69,
	0xde, 0x86, 0x46, 0xa7, 0x00, 0x17, 0x5c, 0x3b, 0xcf, 0x4e, 0x22, 0x1a, 0x43, 0xdf, 0xac, 0x94,
	0x8d, 0x4b, 0xa1, 0xbb, 0x32, 0x22, 0x22, 0x33, 0x7f, 0x1e, 0x2e, 0xff, 0x2e, 0xaa, 0x74, 0xe1,
	0xba, 0x24, 0xcd, 0x8a, 0x5e, 0x42, 0xd8, 0xe2, 0x94, 0xe1, 0xed, 0x41, 0x57, 0x69, 0x56, 0xeb,
	0x16, 0xd9, 0x08, 0xf3, 0x34, 0x93, 0xab, 0x52, 0xb7, 0x39, 0x1a, 0x61, 0xf2, 0xe6, 0x5c, 0x65,
	0xb6, 0x6a, 0x90, 0xd8, 0x79, 0xf9, 0x4e, 0x20, 0x34, 0xb0, 0x6b, 0x5e, 0xaf, 0x45, 0xc6, 0xf1,
	0x14, 0x7a, 0x6d, 0x43, 0x1c, 0x9a, 0xd7, 0x6f, 0xeb, 0x4e, 0x7e, 0xc4, 0xa1, 0xff, 0x5f, 0x3f,
	0x3e, 0xdf, 0xbc, 0x01, 0x0d, 0xe2, 0xf5, 0x51, 0x6c, 0xa2, 0x9d, 0x90, 0x03, 0x3c, 0x87, 0x5e,
	0x1b, 0xae, 0x71, 0x6f, 0x8b, 0xef, 0xb8, 0xf7, 0xad, 0x7b, 0x84, 0x03, 0xe7, 0x8e, 0x9f, 0x45,
	0xfe, 0x82, 0x67, 0x10, 0xb8, 0x72, 0x38, 0xfa, 0x06, 0x30, 0x55, 0x27, 0x03, 0x47, 0xb0, 0x1f,
	0x8b, 0xfe, 0xb3, 0x88, 0x10, 0xfb, 0x0e, 0xa1, 0xd2, 0x3f, 0xf6, 0x0f, 0x38, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x0f, 0xba, 0xc5, 0xaa, 0x37, 0x02, 0x00, 0x00,
}
